### ISSUE TITLE
Do you want to consider upgrading your python scripts?

### ISSUE THREAD

**Issue by wlwtan** [shendurelab/cfDNA#6]
Hi,

 I find it very hard to execute your scripts. 
Are you working on any packages that allow us to do cf-nucleosome analysis?
Thank you.

**Comment by mwsnyder** [comment]
Hello wlwtan,

Thanks for your interest in our work.  I am sorry to hear that you are
having difficulty executing our scripts.  I know that several of the
datasets and software packages that we used at the time have since been
updated to newer versions, and I would strongly recommend that you consider
using updated datasets from Human Protein Atlas or GTEx (among others) if
you are considering studying nucleosome footprints in cfDNA.

At this time, we have no plans to upgrade our python or R scripts.

Best regards,
Matthew Snyder

**Comment by wlwtan** [comment]
Dear Synder,


Thanks for your prompt response.
I have generated my own pilot datasets and was hoping to be able to use your algorithms to look for cell free nucleosome signature, and subsequently infer the cell type origin.

To be specific, im stuck at the stage of nucleosome calling.

Specific questions:
how do you decide the region to look at for nucleosome signatures? TSS? Or is there an updated unbiased way of doing that? Have you tried if usual peak calling algo would work?


Thank you.



Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by wlwtan** [comment]
Thank you, I have resolved this.

**Comment by feihongloveworld** [comment]
> Thank you, I have resolved this.

hi sir：
   do you have any faster method to call  wps of deep wgs data ？

**Comment by makirc** [comment]
No, not at this point.
